
{{- if .Values.gateway.enabled }}
{{ $gatewayName := .Values.gateway.name | default (printf "%s-gw" (include "app.fullname" . )) }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  name: {{ $gatewayName }}
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClass.name }}
  listeners:
    - allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: All
      hostname: {{ include "app.fullname" . }}-k8s-test.ngrok.app
      name: http
      port: 443
      protocol: HTTPS
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  name: {{ include "app.fullname" . }}-default-route
  namespace: {{ .Release.Namespace }}
spec:
  hostnames:
    - {{ include "app.fullname" . }}-k8s-test.ngrok.app
  parentRefs:
    - name: {{ $gatewayName }}
      namespace: {{ .Release.Namespace }}
  rules:
    - backendRefs:
        - name: {{ include "app.fullname" . }}
          port: {{ $.Values.service.port }}
      matches:
        - path:
            value: "/"
{{- end }}